heat_template_version: 2013-05-23

description: |
  PostgreSQL Template 101

parameters:

  ssh_key:
    type: string
    description: Registered key pair for root account
  server_name:
    type: string
    description: Name of the PostgreSQL database instance
    default: pg_server
  image:
    type: string
    description: Server image id to use
    default: Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
    constraints:
    # only tested on Ubuntu images so far
    - allowed_values:
      - Debian 7 (Wheezy) (PVHVM)
      - Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
      description: must be a valid Ubuntu image id
  flavor:
    description: Server flavor id to use
    type: string
    default: 4 GB Performance
    constraints:
    - allowed_values:
      - 4 GB Performance
      description: must be a valid Rackspace Cloud Server flavor.
  db_name:
    description: name of the database
    type: string
    constraints:
    - length:
        min: 1
        max: 63
      description: must be between 1 and 63 characters
      allowed_pattern : "[a-zA-Z][a-zA-Z0-9]*"
      description : must begin with a letter and contain only alphanumeric characters.

resources:
  pgdb_server:
    type: Rackspace::Cloud::Server
    properties:
      name: { get_param: server_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: ssh_key }
      user_data_format: RAW
      config_drive: "true"
      user_data:
        str_replace:
          template: |
            #!/bin/bash -v
            ## Harden some of the things
            export myhostname=`hostname`
            export DEBIAN_FRONTEND=noninteractive
            sudo apt-get update > /dev/null
            sudo apt-get install -y ufw vim
            sudo ufw allow ssh
            sudo ufw allow 5432
            sudo ufw enable
            sudo update-alternatives --set editor /usr/bin/vim.basic
            ## Install and set up sar to run at 5 minute intervals
            sudo apt-get install -y sysstat
            sudo sed -i 's/false/true/g' /etc/default/sysstat
            sudo sed -i 's/5-55\/10/\*\/5/g' /etc/cron.d/sysstat
            sudo service sysstat restart
            ## Setup the official PostgreSQL debian/ubuntu repo
            sudo echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -c | awk '{print $(NF)}')-pgdg main" >> /etc/apt/sources.list.d/pgdg.list
            sudo wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
            sudo apt-get update > /dev/null
            ## set up the data disk
            sudo apt-get install parted xfsprogs
            sudo mkfs -t xfs /dev/xvde1
            sudo mkdir -p /data
            sudo echo '/dev/xvde1          /data  xfs    noatime,noquota,nobarrier      0      2' >> /etc/fstab
            sudo mount -a
            ## Install PostgreSQL
            sudo sysctl -w kernel.shmmax=$(($(free | grep Mem | awk '{print $2}') / 4)) >> /etc/sysctl.conf
            sudo apt-get install -y postgresql-9.3 postgresql-doc-9.3 postgresql-contrib-9.3
            sudo apt-get install -y postgresql-server-dev-9.3
            ## Move PG data directory to the ephemeral disk
            sudo service postgresql stop
            sudo cp -a /var/lib/postgresql/ /data/postgresql
            sudo mv /var/lib/postgresql /var/lib/postgresql-old
            sudo ln -s /data/postgresql /var/lib/postgresql
            sudo service postgresql start
            ## Hold PostgreSQL packages
            echo "postgresql-9.3 hold"  | sudo dpkg --set-selections
            echo "postgresql-client-9.3 hold"  | sudo dpkg --set-selections
            echo "postgresql-client-common hold"  | sudo dpkg --set-selections
            echo "postgresql-common hold"  | sudo dpkg --set-selections
            echo "postgresql-contrib-9.3 hold"  | sudo dpkg --set-selections
            echo "postgresql-doc-9.3 hold"  | sudo dpkg --set-selections
            echo "postgresql-server-dev--9.3 hold"  | sudo dpkg --set-selections
            ## Use pgtune to set base configuration
            sudo apt-get -y install pgtune
            sudo pgtune -T OLTP -i /etc/postgresql/9.3/main/postgresql.conf -o /etc/postgresql/9.3/main/postgresql.conf
            ## Create user, database
            sudo -u postgres psql -c "CREATE DATABASE %db_name%"

          params:
            "%db_name%": { get_param: db_name }

outputs:
  ssh:
    value:
      str_replace:
        template: ssh root@%host%
        params:
          "%host%":
            get_attr:
            - pgdb_server
            - accessIPv4
    description: ssh
  private_ip:
    description: "Private IP of PostgreSQL Database"
    value: { get_attr: [pgdb_server, privateIPv4] }
