heat_template_version: 2013-05-23
 
description: |
  Base Template
 
parameters:
 
  ssh_key:
    type: string
    description: The registered key pair used for the root account
  server_name:
    type: string
    description: Name of the base instance
    default:
      str_replace:
        template: stack_name_base_server
        params:
          stack_name: { get_param: "OS::stack_name" }
  image:
    type: string
    description: Server image id to use
    default: Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
    constraints:
    # only tested on Ubuntu images so far
    - allowed_values:
      - Debian 7 (Wheezy) (PVHVM) 
      - Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
      description: must be a valid Ubuntu image id
  flavor:
    description: Server flavor id to use
    type: string
    default: 4 GB Performance
    constraints:
    - allowed_values:
      - 120 GB Performance
      - 90 GB Performance
      - 60 GB Performance
      - 30 GB Performance
      - 4 GB Performance
      description: must be a valid Rackspace Cloud Server flavor.
 
resources:
  base_server:
    type: OS::Nova::Server
    properties:
      name: { get_param: server_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: ssh_key }
      user_data_format: RAW
      config_drive: "true"
      user_data: |
        #!/bin/bash -v
        ## Harden some of the things
        export DEBIAN_FRONTEND=noninteractive
        export myhostname=`hostname`
        sudo apt-get install -y ufw
        sudo ufw allow ssh
        sudo ufw enable
        sudo apt-get update 
        sudo useradd -s /bin/bash -m -G sudo letterj
        
 
outputs:
  ssh:
    value:
      str_replace:
        template: ssh root@%host%
        params:
          "%host%":
            get_attr:
            - base_server
            - accessIPv4
    description: ssh
